Repository SoulGames/Website, pull requests merged in 2020-06, with the labels that each got.

#26 Change the meta language admin/addChange
  changes/index.php
Labels: fix

#33 🔒 Fixed a security issue
  admin/addBeta/index.php
  admin/addChange/index.php
  admin/index.php
Labels: fix, security

#34 🚑 Hotfix a var name
  admin/addBeta/index.php
  admin/addChange/index.php
  admin/controller.php
Labels: fix, hotfix

#35 🔒 Fixed the 'password bypass'
  admin/addBeta/index.php
  admin/addChange/index.php
  admin/controller.php
  admin/logout.php
Labels: fix, security

#37 Update
  README.md
  admin/addBeta/index.php
  admin/addChange/index.php
  beta/index.php
  changes/index.php
  impressum/index.html
  index.html
  kontakt/index.html
  news/index.html
  robots.txt
  team/index.html
Labels: enhancement, fix, security, update

#40 ✨ Added <noscript> (#38)
  beta/index.php
  changes/index.php
  impressum/index.html
  index.html
  kontakt/index.html
  maintenance/index.html
  news/index.html
  team/index.html
Labels: enhancement
